// 記事メタデータ（本文は posts/{slug}.md に分離）
const posts = [
  {
    "title": "今日のAI最前線：Anthropicが仕掛けるSaaS革命とNvidiaの投資戦略の転換",
    "title_en": "# Today's AI Frontline: The SaaS Revolution Anthropic is Driving and Nvidia's Shift in Investment Strategy",
    "title_zh-tw": "今日的AI前沿：Anthropic發起的SaaS革命與Nvidia投資戰略的轉變",
    "title_zh-cn": "今天的AI最前线：Anthropic发起的SaaS革命与Nvidia投资战略的转变",
    "title_ko": "오늘의 AI 최전선: Anthropic이 추진하는 SaaS 혁명과 Nvidia의 투자 전략 전환",
    "category": "AI NEWS",
    "date": "2026.03.05",
    "thumbnail": "",
    "summary": "Anthropicの新機能がSaaS企業の株価を急落させ、NvidiaのCEOがOpenAIとAnthropicへの投資を引き上げると発表。AI業界の勢力図が大きく変わる週となっました。",
    "summary_en": "Anthropic's new features caused SaaS company stock prices to plummet, and Nvidia's CEO announced it would increase investments in OpenAI and Anthropic. This week marked a significant shift in the AI industry's power dynamics.",
    "summary_zh-tw": "Anthropic 的新功能導致 SaaS 企業股價急跌，Nvidia 執行長宣布提高對 OpenAI 和 Anthropic 的投資。本週 AI 業界的勢力版圖出現重大變化。",
    "summary_zh-cn": "Anthropic 的新功能导致 SaaS 企业股价暴跌,英伟达首席执行官宣布将增加对 OpenAI 和 Anthropic 的投资。这一周 AI 行业的格局发生了重大变化。",
    "summary_ko": "Anthropic의 새로운 기능이 SaaS 기업의 주가를 급락시켰고, Nvidia의 CEO가 OpenAI와 Anthropic에 대한 투자를 늘린다고 발표했습니다. AI 업계의 세력도가 크게 변하는 주간이 되었습니다.",
    "slug": "2026-03-05"
  },
        {
    "title": "プロンプトテクニック ~基礎編~",
    "title_en": "Prompt Techniques ~Basic Edition~",
    "title_zh-tw": "提示詞技巧 ~基礎篇~",
    "title_zh-cn": "提示词技巧 ~基础篇~",
    "title_ko": "프롬프트 기술 ~기초편~",
    "category": "For Beginner",
    "date": "2026.03.04",
    "thumbnail": "images/prompt-technique.png",
    "summary": "AIの回答は、私たちが指示する内容（プロンプト）によって精度がかなり変わります。より良い回答が得られるためのテクニックをご紹介します。",
    "summary_en": "The quality of AI responses varies considerably depending on the content we instruct it to provide (the prompt). Here are some techniques for obtaining better responses.",
    "summary_zh-tw": "AI的回答根據我們指示的內容（提示詞）精度會有相當大的差異。以下介紹一些能獲得更佳回答的技巧。",
    "summary_zh-cn": "AI的回答精度会根据我们指示的内容（提示）而有很大差异。以下是为您获取更好回答的技巧。",
    "summary_ko": "AI의 응답은 우리가 지시하는 내용(프롬프트)에 따라 정확도가 상당히 달라집니다. 더 나은 응답을 얻기 위한 기법을 소개합니다.",
    "slug": "2026-03-04-2"
  },
  {
    "title": "今日のAI最前線：Microsoft Build 2026、Alibaba Qwen体制変更、生成AIの人材育成課題が話題に",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.03.04",
    "thumbnail": "",
    "summary": "Microsoft Build 2026がサンフランシスコで開催予定、Alibaba Qwenの技術責任者が退任、生成AIが若手のスキル獲得に影響する可能性が業界で議論されています。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-04"
  },
    {
    "title": "今週のAI最前線：ChatGPTの政府契約で波紋、Claudeが利用者を勢力拡大中",
    "title_en": "# AI Front Lines This Week: Ripples from ChatGPT's Government Contract, Claude Gaining Users",
    "title_zh-tw": "本週AI前線：ChatGPT政府合約引發波瀾，Claude用戶勢力持續擴大",
    "title_zh-cn": "本周AI前沿动态：ChatGPT政府合同引发波澜，Claude用户势力扩大",
    "title_ko": "이번 주 AI 최전선: ChatGPT의 정부 계약으로 파문, Claude가 사용자 세력 확대 중",
    "category": "AI NEWS",
    "date": "2026.03.03",
    "thumbnail": "",
    "summary": "AIアシスタント市場が激動。ChatGPTは国防総省との契約で大波紋、一方Claudeはメモリ機能を無料プランに拡大し利用者増を狙う。Cursorは年間売上20億ドル突破。",
    "summary_en": "The AI assistant market is in turmoil. ChatGPT makes waves with a Department of Defense contract, while Claude expands memory features to free plans to attract more users. Cursor surpasses $2 billion in annual revenue.",
    "summary_zh-tw": "AI助手市場掀起波瀾。ChatGPT因與國防部簽訂合約引發軒然大波，另一方面Claude則將記憶功能擴展至免費方案以吸引更多用戶。Cursor年度銷售額突破20億美元。",
    "summary_zh-cn": "AI助手市场动荡。ChatGPT与国防部签约引发波澜，而Claude则将内存功能扩展到免费计划以争取更多用户。Cursor年销售额突破20亿美元。",
    "summary_ko": "AI 어시스턴트 시장이 급변 중. ChatGPT는 국방부 계약으로 큰 파장을 일으키고 있으며, 한편 Claude는 메모리 기능을 무료 플랜으로 확대하여 사용자 증가를 노린다. Cursor는 연간 매출 20억 달러를 돌파했다.",
    "slug": "2026-03-03"
  },
  {
    "title": "ハルシネーションを減らすためのプロンプト",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "For Beginner",
    "date": "2026.03.02",
    "thumbnail": "images/hallucination.png",
    "summary": "AIは間違った情報を回答することがあります。それを防ぐための方法を説明します。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-02-2"
  },
  {
    "title": "今日のAI最前線：軍事利用から生成AIエージェント時代へ、AI依存の現実が浮き彫りに",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.03.02",
    "thumbnail": "",
    "summary": "米軍がClaudeを実戦投入、CEOの9割がAIエージェント成果に確信、会社員7割が「AI依存」を自覚。音楽生成AIやAIアシスタントなど、AIが生活と仕事に深く浸透する状況が加速しています。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-02"
  },
  {
    "title": "今週のAI最前線：Anthropic vs 米政府、OpenAIの防衛契約、そして資金調達の大型発表",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.03.01",
    "thumbnail": "",
    "summary": "AI業界で激動の1週間。米政府がAnthropicを排除、OpenAIが国防総省と契約、17兆円超の資金調達を発表。AI安全策をめぐる対立が加速し、業界全体の再編が進行中。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-01"
  },
  {
    "title": "今日のAI最前線：Anthropic vs. ペンタゴン、ChatGPT9億ユーザー到達",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.28",
    "thumbnail": "",
    "summary": "トランプ政権がAnthropicを政府から排除、ChatGPTが9億ウィークリーユーザーを達成、AI音楽生成Sunoが200万有料購読者突破。AIの規制と利用をめぐる激動の一週間。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-28"
  },
  {
    "title": "メタプロンプトという考え方",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "For Beginner",
    "date": "2026.02.27",
    "thumbnail": "images/meta-prompting.png",
    "summary": "基本的にはAIにプロンプトを書かせれば大概うまくいきますので、それについてご紹介します。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-27"
  },
  {
    "title": "今週のAI最前線：AIコード支援ツール進化から日本のデータセンター展開まで",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.27",
    "thumbnail": "",
    "summary": "AWSの新型AIコードエディタ「Kiro 0.9」リリース、香川県の廃校をNVIDIA GPU搭載データセンターに転用、Backlog AIアシスタントの正式リリース予定など、AI関連の重要なニュースが続々登場しています。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-27-2"
  },
  {
    "title": "今日のAI最前線：企業向けAIエージェント続々登場、ロボティクス企業がGoogleに統合",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.26",
    "thumbnail": "",
    "summary": "日本企業がオーダーメイド型AIエージェントや管理職向け対話トレーニングを提供開始。一方、GoogleはロボティクスソフトウェアのIntrinsicを傘下に統合し、AI活用の新段階へ。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-26"
  },
  {
    "title": "今日のAI最前線：ネットワーク保守AIと農業生成AIが商用化へ",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.25",
    "thumbnail": "",
    "summary": "国立国会図書館のOCRツール公開、ネットワーク保守向けAIエージェントの商用化、vRAN基盤でのAIアプリ運用実証、農業×生成AIの社会実装、そしてロボティック装具の開発進展など、AI・ロボティクス関連の複数のニュースが報じられました。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-25"
  },
  {
    "title": "今日のAI最前線：防衛省が生成AI活用、クレッシェンドがAIネイティブCDP搭載",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.24",
    "thumbnail": "",
    "summary": "防衛省が国会答弁資料作成に生成AIを導入、クレッシェンド・ラボがAIデータ分析エンジンを強化、日本発のクリエイター育成AIプラットフォームがローンチするなど、AI活用が急速に広がっている。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-24"
  },
  {
    "title": "今週のAI最前線：OpenAIアルトマンCEOが語るAGI時代、SamsungがPerplexity統合、新型アニメAIモデル登場",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.23",
    "thumbnail": "",
    "summary": "OpenAIのサム・アルトマンCEOがインドでAGI実現の近さを語り、SamsungがGalaxy AIにPerplexityを統合。一方、ComfyUIが開発したアニメ特化画像生成AI「Anima」がSDXLに代わる標準を目指しています。AIインフラ整備の進化と多様なAIエコシステムの形成が加速中です。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-23"
  },
  {
    "title": "今日のAI最前線：Samsungが新AI統合、AIスタートアップの生き残り戦が本格化",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.22",
    "thumbnail": "",
    "summary": "SamsungがPerplexityを統合、OpenAIがChatGPTの悪用監視強化、インドのAIチャットアプリが登場。AIエコシステムの多様化とガバナンスの課題が加速しています。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-22"
  }
];
