// 記事メタデータ（本文は posts/{slug}.md に分離）
const posts = [
  {
    "title": "今日のAI最前線：政治的抵抗運動とAI倫理が話題に",
    "title_en": "# Today's AI Frontline: Political Resistance Movements and AI Ethics in Focus",
    "title_zh-tw": "今日的AI最前線：政治抵抗運動和AI倫理成為熱門話題",
    "title_zh-cn": "今日的AI最前线：政治抵抗运动和AI伦理成为话题焦点",
    "title_ko": "오늘의 AI 최전선: 정치적 저항 운동과 AI 윤리가 화제로",
    "category": "AI NEWS",
    "date": "2026.03.04",
    "thumbnail": "",
    "summary": "AIの政治的影響に関する秘密会議や、AIを使用した地球観測技術など、AI業界における重要なニュースが続々と報告されています。",
    "summary_en": "Significant news continues to emerge from the AI industry, including secret meetings regarding AI's political influence and Earth observation technology using AI.",
    "summary_zh-tw": "關於AI的政治影響的秘密會議，以及使用AI的地球觀測技術等，AI業界持續報導重要新聞。",
    "summary_zh-cn": "关于AI的政治影响的秘密会议和使用AI的地球观测技术等，AI行业中的重要新闻不断被报道。",
    "summary_ko": "AI의 정치적 영향에 관한 비밀 회의나 AI를 사용한 지구 관측 기술 등 AI 산업의 중요한 뉴스가 계속 보도되고 있습니다.",
    "slug": "2026-03-04-3"
  },
  {
    "title": "プロンプトテクニック ~基礎編~",
    "category": "For Beginner",
    "date": "2026.03.04",
    "thumbnail": "images/prompt-technique.png",
    "summary": "AIの回答は、私たちが指示する内容（プロンプト）によって精度がかなり変わります。より良い回答が得られるためのテクニックをご紹介します。",
    "slug": "2026-03-04-2"
  },
  {
    "title": "今日のAI最前線：Microsoft Build 2026、Alibaba Qwen体制変更、生成AIの人材育成課題が話題に",
    "category": "AI NEWS",
    "date": "2026.03.04",
    "thumbnail": "",
    "summary": "Microsoft Build 2026がサンフランシスコで開催予定、Alibaba Qwenの技術責任者が退任、生成AIが若手のスキル獲得に影響する可能性が業界で議論されています。",
    "slug": "2026-03-04"
  },
  {
    "title": "今週のAI最前線：ChatGPTの政府契約で波紋、Claudeが利用者を勢力拡大中",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.03.03",
    "thumbnail": "",
    "summary": "AIアシスタント市場が激動。ChatGPTは国防総省との契約で大波紋、一方Claudeはメモリ機能を無料プランに拡大し利用者増を狙う。Cursorは年間売上20億ドル突破。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-03"
  },
  {
    "title": "ハルシネーションを減らすためのプロンプト",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "For Beginner",
    "date": "2026.03.02",
    "thumbnail": "images/hallucination.png",
    "summary": "AIは間違った情報を回答することがあります。それを防ぐための方法を説明します。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-02-2"
  },
  {
    "title": "今日のAI最前線：軍事利用から生成AIエージェント時代へ、AI依存の現実が浮き彫りに",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.03.02",
    "thumbnail": "",
    "summary": "米軍がClaudeを実戦投入、CEOの9割がAIエージェント成果に確信、会社員7割が「AI依存」を自覚。音楽生成AIやAIアシスタントなど、AIが生活と仕事に深く浸透する状況が加速しています。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-02"
  },
  {
    "title": "今週のAI最前線：Anthropic vs 米政府、OpenAIの防衛契約、そして資金調達の大型発表",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.03.01",
    "thumbnail": "",
    "summary": "AI業界で激動の1週間。米政府がAnthropicを排除、OpenAIが国防総省と契約、17兆円超の資金調達を発表。AI安全策をめぐる対立が加速し、業界全体の再編が進行中。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-03-01"
  },
  {
    "title": "今日のAI最前線：Anthropic vs. ペンタゴン、ChatGPT9億ユーザー到達",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.28",
    "thumbnail": "",
    "summary": "トランプ政権がAnthropicを政府から排除、ChatGPTが9億ウィークリーユーザーを達成、AI音楽生成Sunoが200万有料購読者突破。AIの規制と利用をめぐる激動の一週間。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-28"
  },
  {
    "title": "メタプロンプトという考え方",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "For Beginner",
    "date": "2026.02.27",
    "thumbnail": "images/meta-prompting.png",
    "summary": "基本的にはAIにプロンプトを書かせれば大概うまくいきますので、それについてご紹介します。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-27"
  },
  {
    "title": "今週のAI最前線：AIコード支援ツール進化から日本のデータセンター展開まで",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.27",
    "thumbnail": "",
    "summary": "AWSの新型AIコードエディタ「Kiro 0.9」リリース、香川県の廃校をNVIDIA GPU搭載データセンターに転用、Backlog AIアシスタントの正式リリース予定など、AI関連の重要なニュースが続々登場しています。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-27-2"
  },
  {
    "title": "今日のAI最前線：企業向けAIエージェント続々登場、ロボティクス企業がGoogleに統合",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.26",
    "thumbnail": "",
    "summary": "日本企業がオーダーメイド型AIエージェントや管理職向け対話トレーニングを提供開始。一方、GoogleはロボティクスソフトウェアのIntrinsicを傘下に統合し、AI活用の新段階へ。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-26"
  },
  {
    "title": "今日のAI最前線：ネットワーク保守AIと農業生成AIが商用化へ",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.25",
    "thumbnail": "",
    "summary": "国立国会図書館のOCRツール公開、ネットワーク保守向けAIエージェントの商用化、vRAN基盤でのAIアプリ運用実証、農業×生成AIの社会実装、そしてロボティック装具の開発進展など、AI・ロボティクス関連の複数のニュースが報じられました。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-25"
  },
  {
    "title": "今日のAI最前線：防衛省が生成AI活用、クレッシェンドがAIネイティブCDP搭載",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.24",
    "thumbnail": "",
    "summary": "防衛省が国会答弁資料作成に生成AIを導入、クレッシェンド・ラボがAIデータ分析エンジンを強化、日本発のクリエイター育成AIプラットフォームがローンチするなど、AI活用が急速に広がっている。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-24"
  },
  {
    "title": "今週のAI最前線：OpenAIアルトマンCEOが語るAGI時代、SamsungがPerplexity統合、新型アニメAIモデル登場",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.23",
    "thumbnail": "",
    "summary": "OpenAIのサム・アルトマンCEOがインドでAGI実現の近さを語り、SamsungがGalaxy AIにPerplexityを統合。一方、ComfyUIが開発したアニメ特化画像生成AI「Anima」がSDXLに代わる標準を目指しています。AIインフラ整備の進化と多様なAIエコシステムの形成が加速中です。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-23"
  },
  {
    "title": "今日のAI最前線：Samsungが新AI統合、AIスタートアップの生き残り戦が本格化",
    "title_en": "",
    "title_zh-tw": "",
    "title_zh-cn": "",
    "title_ko": "",
    "category": "AI NEWS",
    "date": "2026.02.22",
    "thumbnail": "",
    "summary": "SamsungがPerplexityを統合、OpenAIがChatGPTの悪用監視強化、インドのAIチャットアプリが登場。AIエコシステムの多様化とガバナンスの課題が加速しています。",
    "summary_en": "",
    "summary_zh-tw": "",
    "summary_zh-cn": "",
    "summary_ko": "",
    "slug": "2026-02-22"
  }
];
